# Generated by Django 2.1.7 on 2019-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(blank=True, max_length=255, null=True)),
                ('document_location', models.CharField(blank=True, max_length=255, null=True)),
                ('storage', models.CharField(max_length=125)),
            ],
        ),
    ]
