# Generated by Django 2.1.7 on 2019-03-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='document_url',
            field=models.URLField(null=True),
        ),
    ]
