# Generated by Django 2.1.7 on 2019-03-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_documentrecord_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='name',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
